# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18Mj4w2UYjHzsk-pxdeLhsDWjfb8ZvSR5
"""

import pandas as pd
baza={
    "FISH":["Tojaliyev.M","Aliyeva.Sh","Valiyev.A","Alijonov.O","Erkinova.D","Rashidov.S","Husanov.Y","Turgunov.K","Fayziyev.H","Soliyeva.U"],
    "Manzili":["Fargona viloyati","Andijon viloyati","Qashqadaryo viloyati","Surhandaryo viloyati","Toshkent viloyati","Xorazim viloyati","Fargona viloyati","Fargona viloyati","Fargona viloyati","Fargona viloyati"],
    "Yoshi":["19","19","19","19","19","19","19","19","20","19"],
    "ish joyi":["Student","Student","Student","Student","Student","Student","Student","Student","Student","Student"],
    "Jinsi":["erkak","ayol","erkak","erkak","ayol","erkak","erkak","erkak","erkak","ayol"]
}
db=pd.DataFrame(baza)
print (db)

filtr=db[db['Jinsi']=="ayol"]
print(filtr)

filtr=db[db['Yoshi']>="20"]
print(filtr)

filtr=db[db['Manzili']=="Fargona viloyati"]
print(filtr)